# Generated by Django 5.0.2 on 2024-03-04 01:36

import matrix_traversal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', matrix_traversal.models.MatrixField(editable=False)),
            ],
        ),
    ]
